#ifndef UNIFIED_GEOMETRY_BUFFER_COMMON_LIBRARY_H
#define UNIFIED_GEOMETRY_BUFFER_COMMON_LIBRARY_H

#define UNIFIED_GEOMETRY_BUFFER_BASE_SET 0//62 // INVESTIGAGE:63 is maximum allowed??
#define UNIFIED_GEOMETRY_BUFFER_PAGE_BYTES_SIZE 16384
#define UNIFIED_GEOMETRY_BUFFER_PAGE_4_BYTES_SIZE UNIFIED_GEOMETRY_BUFFER_PAGE_BYTES_SIZE / 4
#define UNIFIED_GEOMETRY_BUFFER_PAGES_COUNT 8192
#endif