#version 460

#extension GL_GOOGLE_include_directive : require

layout(set = 0, binding = 0) buffer gpuPersistentMemoryBlock
{
	uint gpuPersistentMemory[];
};


#include "GpuDrivenRendering/GpuScene.Library.glsl" //! #include "../GpuDrivenRendering/GpuScene.Library.glsl"
#include "UnifiedUploadHeap.Library.glsl" //! #include "../UnifiedUploadHeap.Library.glsl"



struct GpuTableCreateInfo
{
	uint byteOffset;
	uint reservedSize;
	uint rowSize;
};

#define GPU_TABLE_CREATE_INFO_SIZE 3

GpuTableCreateInfo gpu_table_create_info_decode_from_workgroup(in uint argumentsOffset, in uint count)
{
	GpuTableCreateInfo info;
	info.byteOffset = argumentsOffset;
	info.reservedSize = (count >> 16) & 0xFF;
	info.rowSize = count & 0xFF;
	return info;
}

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;
void gpu_scene_initialize_table()
{
	

	if(gl_GlobalInvocationID.x < reservedSize)
	{
		GpuTableCreateInfo info = gpu_table_create_info_decode_from_workgroup(workgroupItemArguments.argumentsOffset, workgroupItemArguments.count);


		if(gl_GlobalInvocationID.x == 0)
		{
			GpuTableHeader header;
			header.byteOffset = info.byteOffset;
			header.size = 0;
			header.reservedSize = info.reservedSize;

			gpu_table_header_encode(header);
		}

		for(uint i = 0; i < info.rowSize; i++)
		{
			gpuPersistentMemory[info.byteOffset + GPU_TABLE_HEADER_SIZE + gl_GlobalInvocationID.x * i ] = -1;
		}
	}
	
}
